<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net6.0;net7.0;net8.0;net9.0;net10.0</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Assets\Images\**" />
    <EmbeddedResource Remove="Assets\Images\**" />
    <None Remove="Assets\Images\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Assets\Zips\SirHurt.zip" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\Zips\SirHurt.zip" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Serilog" Version="4.3.1" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
  </ItemGroup>

</Project>
